### PR TITLE
remove utils introduced in #12

### PR DESCRIPTION
**Pull request by bicycle1885**
I'd like to propose that removing utility functions introduced in #12: `writegz`, `readgz`, and `gzopen`.
There are some reasons I don't think these are suitable in Libz.jl:
1. Libz.jl is an interface package for zlib, which doesn't offer these functions.
2. Accessing a compressed file by its filename is not a standard way: Neither [zlib of Python3](https://docs.python.org/3/library/zlib.html) nor [Zlib of Node.js](https://nodejs.org/api/zlib.html) does not have such interfaces.
3. These functions are fairly easy to implement; the user can define these things with a few lines of code if necessary.

Any thoughts?

### CODE REVIEW

**Comment by bicycle1885** [comment]
I will apply this change before the next release if no objections.

**Comment by TransGirlCodes** [comment]
I think these are reasonable arguments, and that this is all good.

**Comment by bicycle1885** [comment]
Thanks. I will merge this if tests are green.

**Comment by bicycle1885** [comment]
`Environment: JULIAVERSION=julianightlies/bin/winnt/x64/julia-latest-win64.exe` hangs on AppVeyor. This sometimes happens, and would be harmless because other tests have passed.

**Pull request merged**
