### PR TITLE
Update REQUIRE compat version

### PR DESCRIPTION
**Pull request by musm**
I don't want to spend an hour  trying to figure out the minimum compat version, but this version will be sufficient

### CODE REVIEW

**Comment by tkelman** [comment]
It takes 15 seconds. This is correct for `take!`. https://github.com/JuliaLang/Compat.jl/commit/3541c2df0ccf918b97c5d8b5dadd5aa9b1e3f890

**Comment by musm** [comment]
The real question is how did the tests pass without this correct compat version...

**Comment by tkelman** [comment]
Because minimum version requirements are just that, minimums. If you don't have any upper bounds / pinnings in effect (and Travis generally won't unless some dependency packages have), then you'll get the latest version. But if you selectively update individual packages without updating their dependencies, or apply pinnings / upper bounds, you can get non-latest copies so that's when getting minimum versions right matters.

**Comment by TransGirlCodes** [comment]
Ok, I'll have to apply this to the release retroactively

**Pull request merged**
