### PR TITLE
Add appveyor, run travis on 0.4

### PR DESCRIPTION
**Pull request by tkelman**
You'll have to turn AppVeyor on manually.

### CODE REVIEW

**Comment by tkelman** [comment]
Bump!

**Comment by TransGirlCodes** [comment]
:shipit: - ok one more person take a look - I'm not usually the one that configures travis.

**Comment by tkelman** [comment]
Hi! What does RTR mean? Let me know if you've signed up for AppVeyor and enabled this repo, and I'll rebase to try triggering a build.

**Comment by bicycle1885** [comment]
@tkelman A pull request is tagged as RTR when it is ready to review.

Signing up for AppVeyor seems to require to be an owner of the organization. @Ward9250 can you activate AppVeyor for this and other projects? I'm not an owner of this organization :(

**Comment by tkelman** [comment]
Or someone else can sign up then post the webhook url (from the AppVeyor settings) here, then an owner can set up the webhook as in https://github.com/JuliaOpt/JuMP.jl/pull/362#issuecomment-70610293

**Comment by TransGirlCodes** [comment]
Ok I'll do this later today.

**Comment by tkelman** [comment]
Cool. Looks like there's an issue on win64. Culong is 32 bits on that platform.

**Comment by TransGirlCodes** [comment]
I'm not sure how to fix that, I don't know AppVeyor, and am not familiar with Libz workings. Is this a code issue or AppVeyor config issue?

**Comment by tkelman** [comment]
Code issue. Someone familiar with the code could open a PR to try to fix that. It'll fail on win64 until then, but that's just reflecting reality.

**Comment by TransGirlCodes** [comment]
I was about to download and test to isolate the issue, but then the builds are fine for OSx and Linux so it's probably no issue on my machine.

**Comment by tkelman** [comment]
Yeah, platform difference. Win64 is the only common platform where `UInt != Culong`

**Comment by TransGirlCodes** [comment]
Perhaps this can be solved intelligently with some generated function? The body of the function depending on types or something. But maybe it doesen't even need to be that complex.

**Comment by TransGirlCodes** [comment]
Am I correct in thinking the yaml file for this repo should work with minor modifications for the other repos like Bio.jl? It looks like the name change is really all that's needed.

**Comment by tkelman** [comment]
Should just be a matter of type declarations or conversions somewhere should be explicit about Culong rather than UInt.

Correct, the name is the only thing that would change in thr yml template. Note that all repos under your account will share a single worker, so the queue might get long if these repos are busy or you enable a lot of them. Other collaborators could run some repos on their appveyor accounts, you would just need to change the webhook url and badge links.

**Comment by tkelman** [comment]
there is a snippet here
https://github.com/JuliaOpt/CoinOptServices.jl/blob/6098bcbd2f1d00a20d0893e261c1a38895471959/appveyor.yml#L20-L24
that you could use for the sake of busy PRs, in case they receive many small commits in a row - only the most recent build for a PR is especially relevant

**Pull request merged**
