### PR TITLE
Convenience functions for dealing with .gz files

### PR DESCRIPTION
**Pull request by samoconnor**
Convenience functions to read/write directly from/to a named file.

I'm doing a cleanup of my local stash of convenience functions and thought that these might be generally useful.

``` julia
gzwrite("/tmp/foo.gz", "hello")
gzreadall("/tmp/foo.gz")
"hello"
```

See also https://github.com/JuliaLang/GZip.jl/pull/45#issuecomment-169565175

Also, the example in README.md doesn't work...

``` julia
stream = open("data.txt.gz", "w") |> ZlibDeflateOutputStream
for c in rand(UInt8, 10000)
    write(stream, c)
end
close(stream)
```

The underlying file needs to be closed to ensure that the file is completely written...

``` julia
io = open("data.txt.gz", "w")
stream = ZlibDeflateOutputStream(io)
for c in rand(UInt8, 10000)
    write(stream, c)
end
close(stream)
close(io)
```

The `gzopen(::Function...)` methods in the PR make this easier by supporting `gzopen("foo.gz") do io...` syntax.

### CODE REVIEW

**Comment by tkelman** [comment]
You can't export the same names from multiple packages.

**Comment by samoconnor** [comment]
Hi @tkelman,  re name clash across packages: @kmsquire [suggested that Gzip.jl is depricated-ish  in favour of Libz.jl](https://github.com/JuliaLang/GZip.jl/pull/45#issuecomment-169565175), so I move the PR over to here.

More generally though, I imagine that its a useful pattern to have the same names from multiple packages if they really do the same thing. That would allow easy plug ability of alternate implementations.

**Comment by tkelman** [comment]
Except that packages aren't always exactly drop in replacements (if they were they'd just be new versions instead of separate packages), and different downstream users have different requirements, including the ability to use both simultaneously.

**Comment by tkelman** [comment]
If you want to extend the same generic function with new methods that makes complete sense, but you have to agree where the generic function is defined and extended from, and use completely disjoint type signatures for all methods.

**Comment by samoconnor** [comment]
bump

https://github.com/JuliaLang/julia/pull/14660 is now merged

This PR makes the gz interface more consistent with ::IO is base.

**Comment by TransGirlCodes** [comment]
Awesome! Is there any chance of increasing the code coverage a bit before a merge? codecov is telling me it has fallen as a result of the PR.

**Comment by samoconnor** [comment]
> any chance of increasing the code coverage a bit before a merge?

done

**Comment by blahah** [comment]
@samoconnor that was fast!

if CI checks pass, LGTM :shipit:

**Comment by TransGirlCodes** [comment]
Only appveyor fails, but it was failing before. I don't think it's a PR specific failing. :shipit:

**Pull request merged**
